image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\pclink11
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - Win32

configuration:
  - Debug
  - Release

environment:
  matrix:
    - toolchain: msvc13

build:
  project: pclink11.sln

test_script:
  - cmd: cd tests
  - cmd: !runtestmy.cmd
  - cmd: cd ..
  - cmd: %CONFIGURATION%\testanalyzer.exe
