language: cpp

sudo: required

matrix:
  include:
    - { os: linux, dist: trusty, compiler: gcc }
    - { os: linux, dist: trusty, compiler: clang }
    - { os: linux, dist: xenial, compiler: clang }
    - { os: linux, dist: bionic, compiler: clang }
    - { os: linux, dist: focal, compiler: clang }
    - { os: osx, compiler: clang }

script:
  - make
  - testrunner/testrunner
  - testanalyzer/testanalyzer
